version: '3'
services:
  giornale-db:
    image: mysql
    environment:
      - MYSQL_DATABASE=giornale
      - MYSQL_ROOT_PASSWORD=pa55word
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pa55word --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  giornale-app:
    build: .
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      - MYSQL_HOST=giornale-db
      - MYSQL_PORT=3306
    depends_on:
      - giornale-db